name: CI

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
 
  linux-build:
    
    runs-on: [self-hosted,ubuntu-latest]
    
    defaults:
      run:
        working-directory: ./backend
        
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
    
    steps:
      
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: install dependencies
        run: | 
          npm install
          npm run build --if-present
          npm init @eslint/config

      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
      - uses: actions/eslint-action@1.0.2
        with:
          files: src/
          
  windows-build:
  
      runs-on: windows-latest
      
      defaults:
        run:
          working-directory: ./frontend
          
      strategy:
        matrix:
          node-version: [14.x, 16.x, 18.x, 20.x]
        
      steps:
        - uses: actions/checkout@v3
        - name: Install dependencies
          run: |
            npm install
            npm run build --if-present
            npm test
        - name: Archive production artifacts
          uses: actions/upload-artifact@v3
          with:
            name: dist-without-markdown
            path: |
              dist
              !dist/**/*.md
        - name: Archive code coverage results
          uses: actions/upload-artifact@v3
          with:
            name: code-coverage-report
            path: output/test/code-coverage.html
